#!/bin/bash
# Name of the job
#$ -N linear15
#$ -pe mpi 4
#$ -t 1-4
#$ -q scc
##$ -m eba
##$ -M konstantin.beck@uni.kn
#$ -l h_vmem=2G
#$ -l ib

module load lammps

date=$(date +%d_%m-%H%M)
startTemp=0.5
temp=$(bc <<< "0.4+0.1*${SGE_TASK_ID}") 
tempstr=$(bc <<< ${temp}*10/1)
printf -v j "%02d" ${tempstr}
dir=scc_${NSLOTS}_temp10_$j-${date}

mkdir $dir
cp in.lj job_juwels.sub $dir/.
cd $dir

mpirun -n ${NSLOTS} lmp -v startTemp ${startTemp} -v temp ${temp} -in in.lj >> out
