#!/bin/bash
# Name of the job
#$ -N ljGPU
##$ -pe mpi 1
#$ -l gpu=1
#$ -q scc 
#$ -m eba
#$ -M konstantin.beck@uni.kn
#$ -l h_vmem=2G
#$ -l ib
#rm -f image.*
#rm -f *.avi
#rm -f log.lammps
#rm -f out

date=$(date +%d_%m-%H%M)                                                                                                                 \

dir=gpu_$date
mkdir $dir
cp in.rigid $dir/.
cp data.* $dir/.
cp job.sub $dir/.
cd $dir

module load lammps

lmp -sf gpu -echo screen -in in.rigid >>out
