#!/bin/bash
# Name of the job
#$ -N random64_64
#$ -pe mpi 64
#$ -q scc 
#$ -m eba
#$ -M konstantin.beck@uni.kn
#$ -l h_vmem=2G
#$ -l ib
#rm -f image.*
#rm -f *.avi
#rm -f log.lammps
#rm -f out

date=$(date +%d_%m-%H%M)                                                                                                    

dir=64_64cubes_$date
mkdir $dir
cp in.cubes data.rigid job.sub $dir/.
cd $dir

module load lammps

mpirun -n $NSLOTS lmp -echo screen -in in.cubes >>out
