
Currently Loaded Modules:
  1) [2mGCCcore/.9.3.0[0m         (H)    25) [2mfontconfig/.2.13.92[0m      (H)  49) tbb/2020.3
  2) [2mzlib/.1.2.11[0m           (H)    26) [2mxorg-macros/.1.19.2[0m      (H)  50) [2mPCRE/.8.44[0m                    (H)
  3) [2mbinutils/.2.34[0m         (H)    27) [2mlibpciaccess/.0.16[0m       (H)  51) [2mx264/.20200912[0m                (H)
  4) StdEnv/2020                   28) X11/20200222                  52) [2mLAME/.3.100[0m                   (H)
  5) GCC/9.3.0                     29) [2mTk/.8.6.10[0m               (H)  53) [2mx265/.3.4[0m                     (H)
  6) numactl/2.0.13                30) GMP/6.2.0                     54) libvpx/1.9.0
  7) [2mnvidia-driver/.default[0m (H,[1;31mg[0m)  31) [2mlibxslt/.1.1.34[0m          (H)  55) FriBidi/1.0.9
  8) CUDA/11.0              ([1;31mg[0m)    32) [2mlibffi/.3.3[0m              (H)  56) [2mFFmpeg/.4.3.1[0m                 (H)
  9) UCX/1.9.0                     33) [2mlibyaml/.0.2.5[0m           (H)  57) Voro++/0.4.6
 10) [2mpscom/.5.4-default[0m     (H)    34) Java/1.8_292-b10-OpenJDK      58) CMake/3.18.0
 11) [2mXZ/.5.2.5[0m              (H)    35) PostgreSQL/12.3               59) kim-api/2.1.3
 12) [2mlibxml2/.2.9.10[0m        (H)    36) [2mprotobuf/.3.13.0[0m         (H)  60) Eigen/3.3.7
 13) mpi-settings/UCX-plain        37) [2mgflags/.2.2.2[0m            (H)  61) SciPy-Stack/2020-Python-3.8.5
 14) ParaStationMPI/5.4.7-1 ([1;31mg[0m)    38) [2mlibspatialindex/.1.9.3[0m   (H)  62) mpi4py/3.0.3-Python-3.8.5
 15) [2mbzip2/.1.0.8[0m           (H)    39) [2mNASM/.2.15.03[0m            (H)  63) h5py/2.10.0-Python-3.8.5
 16) [2mncurses/.6.2[0m           (H)    40) [2mlibjpeg-turbo/.2.0.5[0m     (H)  64) yaff/1.6.0-Python-3.8.5
 17) [2mlibreadline/.8.0[0m       (H)    41) Python/3.8.5                  65) imkl/2020.2.254
 18) Tcl/8.6.10                    42) [2mSzip/.2.1.1[0m              (H)  66) [2mlibmatheval/.1.1.11[0m           (H)
 19) [2mSQLite/.3.32.3[0m         (H)    43) HDF5/1.10.6                   67) PLUMED/2.6.1
 20) [2mexpat/.2.2.9[0m           (H)    44) cURL/7.71.1                   68) FFTW/3.3.8
 21) [2mlibpng/.1.6.37[0m         (H)    45) parallel-netcdf/1.12.1        69) ScaFaCoS/1.0.1
 22) [2mfreetype/.2.10.1[0m       (H)    46) netCDF/4.7.4                  70) LAMMPS/24Dec2020
 23) [2mgperf/.3.1[0m             (H)    47) GSL/2.6
 24) [2mutil-linux/.2.36[0m       (H)    48) [2mgzip/.1.10[0m               (H)

  Where:
   [1;31mg[0m:  built for GPU
   H:             Hidden Module

 

