#!/bin/bash
# Name of the job
#$ -N mixopt32
#$ -pe mpi 32
#$ -q scc 
#$ -m eba
#$ -M konstantin.beck@uni.kn
#$ -l h_vmem=2G
#$ -l ib
#rm -f image.*
#rm -f *.avi
#rm -f log.lammps
#rm -f out

date=$(date +%d_%m-%H%M)                                                                                                    

dir=32_$date
mkdir $dir
cp in.solvent in.cubes data.restart data.cubes job.sub $dir/.
cd $dir

module load lammps

mpirun -n $NSLOTS lmp -echo screen -in in.solvent >>out
