#!/bin/bash -x
#SBATCH --account="tncscg"
#SBATCH --job-name=linear
#SBATCH --nodes=2
#SBATCH --ntasks=96
#SBATCH --ntasks-per-node=48
#SBATCH --time=7:00:00
#SBATCH --partition=batch
#SBATCH --array=1-5
# *** start of job script ***
# Note: The current working directory at this point is
# the directory where sbatch was executed.

date=$(date +%d_%m-%H%M)
startTemp=1.0
temp=1.0
echo temp = ${temp}
tempstr=$(bc <<< ${temp}*10/1)
printf -v j "%02d" ${tempstr}
cutoff=$(bc <<< "1.5+0.2*${SLURM_ARRAY_TASK_ID}")
cstr=$(bc <<< ${cutoff}*10/1)
printf -v c "%02d" ${cstr}


dir=juelich_${SLURM_NTASKS}_cut${c}-${date}

mkdir $dir
cp in.lj data* job_juwels.sub $dir/.
cd $dir

srun -n ${SLURM_NTASKS} lmp -v cutoff ${cutoff} -v startTemp ${startTemp} -v temp ${temp} -in in.lj >> out
