%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /data/scc/kobeck/Master/juelich/mix/100/240_temp08_10-07_06-0012/dump.msd
%
% Auto-generated by MATLAB on 07-Jun-2021 22:37:13

clear all; close all; clc;
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [4, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "Timeaveraged", "data", "for1", "fix"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
dump1 = readtable("/data/scc/kobeck/Master/juelich/mix/100/240_temp08_10-07_06-0012/dump.msd", opts);


%% Clear temporary variables
clear opts

%% plot msd
clearvars -except dump1
steps = 1001;
Natoms = 490;
msd = zeros(490,steps);
ave = zeros(1,steps);
data = zeros(Natoms,steps);

for i = 1:steps
    data(:,i)=dump1{(Natoms+1)*(i-1)+2:(Natoms+1)*i,5};
    ave(i) = mean(data(:,i));
end

figure(1)
plot(ave(1:1000));

% figure(2)
% for j = 1:10:Natoms
%     plot(data(j,1:100));
%     hold on
% end



    
    