%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /data/scc/kobeck/Master/juelich/mix/100/240_temp08_10-07_06-2322/dump.msd
%
% Auto-generated by MATLAB on 08-Jun-2021 18:52:48

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [4, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "Timeaveraged", "data", "for1", "fix"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
dump = readtable("dump.msd", opts);


%% Clear temporary variables
clear opts

%% plot msd 
Natoms = 250;
steps = floor(height(dump(:,1))/(Natoms+1));
data = zeros(steps,Natoms);
ave = zeros(steps,1);

 
 for i =1:steps
     data(i,:) = dump{(Natoms+1)*(i-1)+2:(Natoms+1)*i,5};
     ave(i) = mean(data(i,:));
 end

plot(ave(:));
% for j =1:10:250 
%     plot(data(:,j))
%     hold on
% end
legend off;








