#!/bin/bash
# Name of the job
#$ -N evap256
#$ -pe mpi 256
#$ -q scc 
#$ -m eba
#$ -M konstantin.beck@uni.kn
#$ -l h_vmem=2G
#$ -l ib
#rm -f image.*
#rm -f *.avi
#rm -f log.lammps
#rm -f out

date=$(date +%d_%m-%H%M)                                                                                                    

dir=256_$date
mkdir $dir
cp in.solvent in.cubes restart.dat.1000000 data.cubes job.sub $dir/.
cd $dir

module load lammps

mpirun -n $NSLOTS lmp -echo screen -in in.solvent >>out
